### ISSUE TITLE
assert world.run() == STOP.EXIT failed

### ISSUE THREAD

**Issue by ggrieco-tob** [crytic/optik#71]
Optik compiled from `master` (cd95a610cfdb30e483a13ea8b82047662ae60a37) crashes: 

```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/g/.local/bin/hybrid-echidna", line 8, in <module>
    sys.exit(main())
  File "/home/g/.local/lib/python3.8/site-packages/optik/echidna/__main__.py", line 521, in main
    func(sys.argv[1:])
  File "/home/g/.local/lib/python3.8/site-packages/optik/echidna/__main__.py", line 311, in run_hybrid_echidna_with_display
    raise exc
  File "/home/g/.local/lib/python3.8/site-packages/optik/echidna/__main__.py", line 288, in run_hybrid_echidna_with_display
    run_hybrid_echidna(args)
  File "/home/g/.local/lib/python3.8/site-packages/optik/echidna/__main__.py", line 257, in run_hybrid_echidna
    replay_inputs(new_inputs, contract_file, deployer, cov)
  File "/home/g/.local/lib/python3.8/site-packages/optik/echidna/runner.py", line 81, in replay_inputs
    assert world.run() == STOP.EXIT
AssertionError
```

To reproduce, you can run:

```
$ hybrid-echidna crash.sol --test-mode assertion --contract C
```

using the following contract:  
```solc
contract C {
    event E();
    function f() public {
        emit E();
    }
}
```

**Comment by Boyan-MILANOV** [comment]
It seems the error is caused by an instruction that we don't support yet, I'll investigate. When running `hybrid-echidna` with logs in debug mode we can see the error: 

````
$ hybrid-echidna crash.sol --test-mode assertion --contract C --debug --no-display --log stdout

...
2022-08-18 10:09:39,439 - INFO - Replaying 2 new inputs symbolically...
2022-08-18 10:09:39,439 - DEBUG - Replaying input: -4319403432689703952.txt
2022-08-18 10:09:39,458 - DEBUG - Replaying input: 3291248796485446771.txt
[Error] Sleigh failed to decode instructions in basic block starting at 0x61. Raised the following error: "Sleigh raised a bad data exception: c0x00000061: Unable to resolve constructor"
[Error] Lifter error: MaatEngine::get_asm_inst(): failed to lift instructions
````

I should probably make an issue template that asks people to get the logs and shows how to do it

**Comment by Boyan-MILANOV** [comment]
@ggrieco-tob If you update `pymaat` to `0.6.6` it should work now. It has a patch for the bug that works for the minimised contract you posted
